apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice
  labels:
    app: configservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configservice
  template:
    metadata:
      labels:
        app: configservice
    spec:
      containers:
      - name: configservice
        image: srelabacr123.azurecr.io/configservice:v1
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=0449be47-4a16-46ef-955e-151d12a65bf5;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/;ApplicationId=159c80fb-57a6-4ffd-82d6-fa07de93f884"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
